### ISSUE TITLE
Start date in future always

### ISSUE THREAD

**Issue by renege** [monterail/angular-mighty-datepicker#22]
How to make the Start date always to be in the future?

**Comment by renege** [comment]
@montrail @monterail-deploy if I set this: 
```
$scope.date_from = moment();
    $scope.options_date_from = {callback: _callthis, start: moment().add('day', 2) };
```
it doesnt work anymore.. And if I remove the start from the options, it only makes it possible to select dates in the past en current date is selected.

**Comment by renege** [comment]
hello @montrail @monterail-deploy ?

**Comment by renege** [comment]
cc @Belir @monterail-deploy @jandudulski @monterail

**Comment by renege** [comment]
@Belir @monterail-deploy @jandudulski @monterail > who is actively supporting this repo

**Comment by Belir** [comment]
@renege hey, sorry for long period of time that you have to wait for answer. What do you want to achieve in final code? Please show me the case and send me your code in gist.

**Comment by jandudulski** [comment]
> who is actively supporting this repo

We're very sorry for lack of proper support in our OSS repos. We're working on how can we improve the situation and soon we should be able to put some resources into this. Once again - sorry for that!

**Comment by krabex** [comment]
@renege Your example
`$scope.options_date_from = {callback: _callthis, start: moment().add('day', 2) };` 
won't work because the start option in agnular-mighty-datepicker as you can read in [documentation](http://monterail.github.io/angular-mighty-datepicker/) is not responsible for start/initial day but for:

> start - init datepicker starting from this month 


**You didn't write precisly what you wanted to achieve so:**

- If you wanted to disable selecting dates which are in the past you should use _after_ attribute:

> after: days after this date are enabled to select

```
In JS:
$scope.enableAfter = moment().add(-1, 'day'); // enable dates since today
In HTML:
<mighty-datepicker ng-model="date" after="enableAfter" options="options"></mighty-datepicker>
```

- If you wanted to have selected some date (e.g. from the future) on start you should simply 

```
In JS:
$scope.date = moment().add(2, 'day'); // assign date from the future:
In HTML:
<mighty-datepicker ng-model="date" options="options"></mighty-datepicker>
```
